"""Contracts observed with pinned real producers on synthetic local inputs.

The producer executables are not needed for these tests. The committed corpus
was generated by scripts/regenerate_detector_fixtures.py; its manifest records
the narrower versions, inputs and transformations these tests cover.
"""

from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path
from typing import Any

import pytest
from typer.testing import CliRunner

from secguard.cli.app import app
from secguard.core.detectors import load_report, load_reports
from secguard.core.findings import FindingParseError

CORPUS = Path(__file__).parent / "fixtures/producer_versions"
VERSIONS = {"gitleaks": "8.30.1", "trufflehog": "3.97.9", "detect-secrets": "1.5.0"}
EXPECTED = {
    "gitleaks": [
        ("gitleaks:aws-access-token", "aws-access-key", "high", 2, None),
        ("gitleaks:generic-api-key", "generic-api-key", "low", 3, None),
        ("gitleaks:github-pat", "github-pat", "high", 4, None),
    ],
    "trufflehog": [
        ("trufflehog:AWS", "aws-access-key", "high", 2, False),
        ("trufflehog:Github", "github-pat", "high", 4, False),
    ],
    "detect-secrets": [
        ("detect-secrets:AWS Access Key", "aws-access-key", "high", 2, False),
        ("detect-secrets:GitHub Token", "github-pat", "high", 4, False),
    ],
}
runner = CliRunner()


def report_path(producer: str, case: str) -> Path:
    extension = "jsonl" if producer == "trufflehog" else "json"
    return CORPUS / f"{producer}-{VERSIONS[producer]}" / f"{case}.{extension}"


def read_native(producer: str, case: str = "positive") -> Any:
    content = report_path(producer, case).read_text(encoding="utf-8")
    if producer == "trufflehog":
        return [json.loads(line) for line in content.splitlines() if line.strip()]
    return json.loads(content)


def scalar_strings(value: Any):
    if isinstance(value, str):
        yield value
    elif isinstance(value, dict):
        for item in value.values():
            yield from scalar_strings(item)
    elif isinstance(value, list):
        for item in value:
            yield from scalar_strings(item)


def canaries(producer: str) -> set[str]:
    values = {
        value
        for case in ("positive", "malformed")
        for value in scalar_strings(read_native(producer, case))
        if value.startswith("SECGUARD-PRODUCER-CANARY-")
    }
    if producer == "detect-secrets":
        values.update(
            entry["hashed_secret"]
            for entries in read_native(producer)["results"].values()
            for entry in entries
        )
    assert values, "Each producer must have observable redaction canaries"
    return values


def assert_redacted(producer: str, text: str) -> None:
    for value in canaries(producer):
        assert value not in text, "A producer credential field propagated into secguard output"


def summary(document) -> list[tuple]:
    return sorted(
        (item.rule, item.secret_type, item.severity, item.line, item.verified)
        for item in document.findings
    )


def scan_arguments(producer: str, case: str, tmp_path: Path) -> list[str]:
    waiver_file = tmp_path / "waivers.yaml"
    waiver_file.write_text('schema: "secguard.waiver/v1"\nwaivers: []\n', encoding="utf-8")
    return [
        "scan",
        "check",
        "--input",
        str(report_path(producer, case)),
        "--waivers",
        str(waiver_file),
        "--today",
        "2026-10-05",
        "--fail-on",
        "high",
    ]


def test_provenance_locks_the_real_versions_and_reports():
    manifest = json.loads((CORPUS / "provenance.json").read_text(encoding="utf-8"))
    lock = json.loads((CORPUS / "producer-lock.json").read_text(encoding="utf-8"))
    assert manifest["schema"] == "secguard.producer-fixtures/v1"
    assert {name: item["version"] for name, item in manifest["producers"].items()} == VERSIONS
    assert (
        manifest["source_lock_sha256"]
        == hashlib.sha256((CORPUS / "producer-lock.json").read_bytes()).hexdigest()
    )
    assert (
        manifest["script_sha256"]
        == hashlib.sha256(
            (CORPUS.parents[2] / "scripts/regenerate_detector_fixtures.py").read_bytes()
        ).hexdigest()
    )
    for producer, record in manifest["producers"].items():
        assert record["source"].startswith(("https://github.com/", "https://pypi.org/"))
        assert set(record["cases"]) == {"positive", "clean", "malformed"}
        if producer in lock["binaries"]:
            assert record["entrypoint_sha256"] == lock["binaries"][producer]["binary_sha256"]
        for case, observation in record["cases"].items():
            fixture = CORPUS / observation["fixture"]
            assert fixture == report_path(producer, case)
            assert b"\r" not in fixture.read_bytes(), "Fixture byte hashes require LF on every OS"
            assert observation["fixture_sha256"] == hashlib.sha256(fixture.read_bytes()).hexdigest()
            if case == "malformed":
                assert observation["kind"] == "derived-invalid-input-not-emitted-by-producer"
            else:
                assert observation["exit_code"] == 0
                assert len(observation["observed"]) == (
                    len(EXPECTED[producer]) if case == "positive" else 0
                )
                assert re.fullmatch(r"[0-9a-f]{64}", observation["raw_sha256"])
                assert re.fullmatch(r"[0-9a-f]{64}", observation["input_sha256"])


@pytest.mark.parametrize("producer", VERSIONS)
def test_real_positive_reports_parse_and_classify_with_auto_and_explicit_format(producer, catalog):
    auto = load_report(report_path(producer, "positive"), catalog=catalog)
    explicit = load_report(
        report_path(producer, "positive"), report_format=producer, catalog=catalog
    )

    assert auto == explicit
    assert summary(auto) == sorted(EXPECTED[producer])
    assert {item.path for item in auto.findings} == {"config.env"}
    assert all(item.mapping == "catalog" for item in auto.findings)
    assert all(item.playbook == item.secret_type for item in auto.findings)
    assert all(item.fingerprint for item in auto.findings)
    assert_redacted(producer, auto.model_dump_json(by_alias=True))


@pytest.mark.parametrize("producer", VERSIONS)
def test_real_clean_reports_remain_clean_in_auto_and_explicit_format(producer):
    assert load_report(report_path(producer, "clean")).findings == []
    assert load_report(report_path(producer, "clean"), report_format=producer).findings == []


@pytest.mark.parametrize("producer", VERSIONS)
def test_derived_malformed_reports_fail_without_echoing_values(producer):
    for report_format in ("auto", producer):
        with pytest.raises(FindingParseError) as error:
            load_report(report_path(producer, "malformed"), report_format=report_format)
        assert_redacted(producer, str(error.value))


@pytest.mark.parametrize("producer", VERSIONS)
@pytest.mark.parametrize("case", ["positive", "clean"])
def test_real_reports_keep_gate_and_redaction_contracts_in_every_written_output(
    producer, case, tmp_path, monkeypatch
):
    monkeypatch.chdir(tmp_path)
    destinations = {
        "--json": tmp_path / "canonical.json",
        "--sarif": tmp_path / "report.sarif",
        "--markdown": tmp_path / "report.md",
        "--pr-comment": tmp_path / "comment.md",
        "--remediation": tmp_path / "remediation.json",
    }
    arguments = scan_arguments(producer, case, tmp_path) + [
        "--repository",
        "synthetic/producer-corpus",
    ]
    for flag, destination in destinations.items():
        arguments.extend([flag, str(destination)])
    result = runner.invoke(app, arguments)

    assert result.exit_code == (1 if case == "positive" else 0), result.output
    count = len(EXPECTED[producer]) if case == "positive" else 0
    canonical = json.loads(destinations["--json"].read_text(encoding="utf-8"))
    sarif = json.loads(destinations["--sarif"].read_text(encoding="utf-8"))
    assert len(canonical["findings"]) == count
    assert sarif["version"] == "2.1.0"
    assert len(sarif["runs"][0]["results"]) == count
    remediation = json.loads(destinations["--remediation"].read_text(encoding="utf-8"))
    assert remediation["schema"] == "secguard.remediation/v1"
    assert remediation["repository"] == "synthetic/producer-corpus"
    assert remediation["gate"]["decision"] == ("BLOCK" if case == "positive" else "PASS")
    assert remediation["omitted_waived"] == 0
    assert len(remediation["findings"]) == count
    assert f"{count} active finding(s)" in destinations["--pr-comment"].read_text(encoding="utf-8")
    for text in (
        result.stdout,
        result.stderr,
        *(path.read_text(encoding="utf-8") for path in destinations.values()),
    ):
        assert_redacted(producer, text)


@pytest.mark.parametrize("producer", VERSIONS)
def test_real_positive_normalize_stdout_contains_only_canonical_findings(producer):
    result = runner.invoke(
        app, ["scan", "normalize", "--input", str(report_path(producer, "positive"))]
    )

    assert result.exit_code == 0, result.output
    assert len(json.loads(result.stdout)["findings"]) == len(EXPECTED[producer])
    assert_redacted(producer, result.stdout)
    assert_redacted(producer, result.stderr)


@pytest.mark.parametrize("producer", VERSIONS)
def test_real_positive_markdown_stdout_does_not_echo_producer_fields(producer, tmp_path):
    waiver_file = tmp_path / "waivers.yaml"
    waiver_file.write_text('schema: "secguard.waiver/v1"\nwaivers: []\n', encoding="utf-8")
    result = runner.invoke(
        app,
        [
            "report",
            "--input",
            str(report_path(producer, "positive")),
            "--waivers",
            str(waiver_file),
            "--today",
            "2026-10-05",
        ],
    )

    assert result.exit_code == 0, result.output
    assert "# secguard scan report" in result.stdout
    assert_redacted(producer, result.stdout)
    assert_redacted(producer, result.stderr)


@pytest.mark.parametrize("producer", VERSIONS)
def test_derived_malformed_reports_have_cli_exit_two_and_no_partial_outputs(
    producer, tmp_path, monkeypatch
):
    monkeypatch.chdir(tmp_path)
    destinations = [
        tmp_path / name
        for name in (
            "canonical.json",
            "report.sarif",
            "report.md",
            "comment.md",
            "remediation.json",
        )
    ]
    arguments = scan_arguments(producer, "malformed", tmp_path) + [
        "--repository",
        "synthetic/producer-corpus",
    ]
    for flag, destination in zip(
        ("--json", "--sarif", "--markdown", "--pr-comment", "--remediation"),
        destinations,
        strict=True,
    ):
        arguments.extend([flag, str(destination)])
    result = runner.invoke(app, arguments)

    assert result.exit_code == 2, result.output
    assert all(not destination.exists() for destination in destinations)
    assert "Traceback" not in result.output
    assert_redacted(producer, result.stdout)
    assert_redacted(producer, result.stderr)


def test_the_real_corpus_merges_correlated_findings_without_losing_detector_rules(catalog):
    paths = [report_path(producer, "positive") for producer in VERSIONS]
    document = load_reports(paths, catalog=catalog)
    reverse = load_reports(list(reversed(paths)), catalog=catalog)

    assert len(document.findings) == 3
    assert document == reverse
    for item in document.findings:
        if item.secret_type in {"aws-access-key", "github-pat"}:
            assert sorted([item.scanner, *item.corroborated_by]) == sorted(VERSIONS)
            assert len(item.rules) == 3
            assert item.severity == "high"
            assert item.verified is False
        else:
            assert item.secret_type == "generic-api-key"
            assert item.severity == "low"
    for producer in VERSIONS:
        assert_redacted(producer, document.model_dump_json(by_alias=True))
